version: "3.8"

services:
  dash:
    container_name: dash
    build:
      context: ./
    restart: unless-stopped
    expose:
      - 5000
    volumes:
     - ./:/usr/src
     - ./database:/usr/src/database

  database:
    container_name: sqlite3
    build:
      context: ./database
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./database:/usr/src/database